self: permissionizer/request-token
allow:
  - repository: permissionizer/request-token
    workflow_ref: .github/workflows/build.yaml
    permissions:
      checks: write
      statuses: write
  - repository: permissionizer/request-token
    permissions:
      contents: read
  - repository: permissionizer/server
    permissions:
      contents: read
